RAWDATA:
  INDIR: Y:/CH-CHA_Chamau/20_sonic_ghg/2025/10
  FILENAME_ID: CH-CHA_ec_yyyymmdd-HHMM.csv.gz
  HEADER_FORMAT: 4-row header (rECord files)
  START_DATE: 2025-10-06 10:30
  END_DATE: 2025-10-07 00:00
  PLOT_RAWDATA_AVAILABILITY: 1
  PLOT_RAWDATA_AGGREGATES: 1
FLUX_PROCESSING:
  RUN_FLUX_CALCS: 1
  EDDYPRO_PROCESSING_FILE: F:/TMP/del/CH-CHA_2025_rECord_[IRGA72]_R350-R1+IRGA75-R2+IRGA72-R1.eddypro
OUTPUT:
  OUTDIR: F:/TMP/del
  OUTDIR_PREFIX: testing
  PLOT_SUMMARY: 1
AFTER PROCESSING:
  DELETE_UNCOMPRESSED_ASCII_AFTER_PROCESSING: 1
